apiVersion: v1
data:
  X-Different-Name: "true"
  X-Request-Start: t=${msec}
  X-Using-Nginx-Controller: "true"
  Access-Control-Allow-Origin : "*"
kind: ConfigMap
metadata:
  name: custom-headers
  namespace: ingress-nginx
